spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jwt:
  secret: X7k9pM2qJ4rL8vN6bH3yT5wZ1xC4dF6gR9jP2mQ8uY5tW3eV0iA6sK4oL7nJ9hB2cD5fG8rT1vY4mP6qW3xZ9jL2kN5hB8rT0vC4dF6g # Thay bằng chuỗi ngẫu nhiên mạnh
  expiration: 86400000

google:
  clientId: your_google_client_id_here # Thêm Client ID từ Google
